"""initial migration

Revision ID: 422d5cd76ce7
Revises: 
Create Date: 2018-08-22 06:15:01.758240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422d5cd76ce7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(length=20), nullable=True),
    sa.Column('engine_type', sa.String(length=20), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('retail_price', sa.Integer(), nullable=False),
    sa.Column('since', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('items', sa.PickleType(), nullable=False),
    sa.Column('last_date_of_sale', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('retail_price', sa.Integer(), nullable=False),
    sa.Column('part_name', sa.String(length=20), nullable=False),
    sa.Column('part_type', sa.String(length=20), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('number_of', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('date_registered', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('spares')
    op.drop_table('customer')
    op.drop_table('blacklist_tokens')
    op.drop_table('bike')
    # ### end Alembic commands ###
